### ISSUE TITLE
[QUESTION] Will this mod ever be backported to 1.7.10?

### ISSUE THREAD

**Issue by warrenher** [TelepathicGrunt/UltraAmplifiedMod#1]
1.7.10 still is a very popular version for modding and, as there is not a single mod in 1.7.10 just like yours, will this mod ever be backported to 1.7.10? Obviously, stuff like the end biome would have to either be changed or removed.
You don't have to do that if you don't want to, I just absolutely love your world generation and kind of miss it when playing on 1.7.10.

**Comment by TelepathicGrunt** [comment]
Sorry but I will only be moving forward in time, not backwards. If you or another modder wish to backport this mod to 1.7.10, feel free to do so as that is why I have this mod open sourced! But my prediction is that newer versions of Minecraft will become more popular for mods as forge just released a stable version of 1.14.4 and many other mods are now planning on porting to 1.14.4.

I will close this issue but thank you for your suggestion.
