### ISSUE TITLE
Vampirism mod & Ultra Amplified

### ISSUE THREAD

**Issue by ClaudiusMinimus** [TelepathicGrunt/UltraAmplifiedMod#10]
I'm using your [Ultra Amplified Dimension](https://www.curseforge.com/minecraft/mc-mods/ultra-amplified-mod/files/2905852) mod (version 1.15.2-7.3.0)  as the overworld for a 1.15 pack that I'm working on. One of the mods I've added is [Vampirism](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire). Vampires, do spawn, but vampire hunters, the Vampire Biome and Vampire Castle are not spawning. I've used [Nature's Compass](https://www.curseforge.com/minecraft/mc-mods/natures-compass) to search for the vampire biome and while it is listed in the compass database, it says that it is not found.  

Is this something you can look into?
Thank you,
CM

**Comment by TelepathicGrunt** [comment]
Does the Vampire structures spawn in vanilla biomes or only in Vampire Biome? If they are only spawnable in the Vampire Biome, you'll have to turn on the importAllModdedBiomes config in Ultra Amplified Dimension's config (which can be found in the serverconfig folder inside the world's own save folder). That config will add all modded biomes into the UA dimension and so, that biome will now spawn. (If you just want the Vampire Biome to spawn in the dimension, you will have to blacklist all other mod's biomes in the same config file)

Try turning that on and see if the biome now spawns with that mob and castle. If it still can't be found, I'll take a look then and see whats up. Hopefully that will work!

**Comment by ClaudiusMinimus** [comment]
Thank you for your reply. The hunters spawn in any biome from what i've seen, but I will check the configs in the morning and test further. I'll also test with only the Vampire mod and UA dimension loaded.

**Comment by ClaudiusMinimus** [comment]
Using importAllModdedBiomes=true now generates the Vampire biome, but no vampire hunters NPCs or vampire castle, though it is getting late, so I'll test more in the morning.

**Comment by TelepathicGrunt** [comment]
I got around to testing it myself and turning on importModdedMobs config makes the vampires spawn correctly in the UA biomes. I also turned on importModdedStructure and importModdedFeatures and now the UA biomes spawns vampirism's hunter camps!

However, I didn't see the castle and when I check vampirism's 1.15 codebase, it seems they haven't added the castle yet to 1.15. <https://github.com/TeamLapen/Vampirism/tree/1.15/src/main/java/de/teamlapen/vampirism/world/gen/structures>
<https://github.com/TeamLapen/Vampirism/tree/1.15/src/main/java/de/teamlapen/vampirism/world/gen/features>

When they do add the castle, it should start spawning correctly. But if it does spawn in Overworld biomes and it isn't spawning in UA biomes, just let me know and I'll look into how the castle is spawned! :)

**Comment by ClaudiusMinimus** [comment]
Thank you very much! I'll test those changes this morning.

**Comment by ClaudiusMinimus** [comment]
It worked! Thanks! 
Is there any way to have these settings so that they are automatically set to true for any newly generated worlds?

**Comment by TelepathicGrunt** [comment]
There is indeed! Copy the UA config file and paste it in the defaultconfigs folder which is above the mod folder that holds the mods. Now newly created future worlds will copy that config file and its settings into the new world's own serverconfig folder. I'll close this issue now that everything is working. Have fun! :)
