### ISSUE TITLE
Possible Corrupt Newly Generated Region/Chunk

### ISSUE THREAD

**Issue by ClaudiusMinimus** [TelepathicGrunt/UltraAmplifiedMod#17]
I'm not sure if this is a UA issue. I had a player on our test server at a location where he kept timing out. However, other players on the server were not affected, including me. I /tp to him and then I too timed out. At that point, neither of us could join the world. BTW: It was a freshly generated chunk. When we /tp ourselves via ssh console to spawn, we were able to enter the world again. We thought it must be a corrupt chunk/region. Here is the location where I timed-out -5570, 99, 9226.

- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.0
- ultra_amplified_dimension-1.15.2-8.0.2

[latest.log](https://github.com/TelepathicGrunt/UltraAmplifiedMod/files/4719854/latest.log)

[r.-11.-19.mca.zip](https://github.com/TelepathicGrunt/UltraAmplifiedMod/files/4719858/r.-11.-19.mca.zip)

**Comment by TelepathicGrunt** [comment]
Holy moley! That's a huge crashlog full of broken loottables lmao. But yeah, it looks like it got cutoff. Was that the entire log ending at 
```
[02Jun2020 23:30:55.419] [Server thread/WARN] [net.minecraft.world.TrackedEntity/]: Fetching packet for removed entity ItemEntity['Air'/17021, l='world', x=8683.56, y=134.00, z=9807.50]
[02Jun2020 23:30:57.820] [Server thread/WARN] [net.minecraft.world.TrackedEntity/]: Fetching packet for removed entity ItemEntity['Air'/17113, l='world', x=8683.95, y=134.00, z=9806.34]
```
Or is there more in the original? If there's more, can you copy the last 80 lines or so and show me that? 

If there's nothing there, then that makes it really problematic as that would suggest there's an infinite loop caused (most likely) by mod incompatibility and that's very difficult to track down.

**Comment by ClaudiusMinimus** [comment]
I'm going through the logs to take care of the other issues. The latest.log attached above is the most complete log I have. Hopefully, issue [18](https://github.com/TelepathicGrunt/UltraAmplifiedMod/issues/18) fixes this issue too.

**Comment by TelepathicGrunt** [comment]
Closing as 1.16.4 release is soon and 1.15.4 support is now being dropped as a result.
