### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by Claycorp** [TelepathicGrunt/UltraAmplifiedMod#2]
https://pastebin.com/4j3EZpAt

**Comment by Claycorp** [comment]
Could have been my fault, I was stepping through trying to pinpoint it and found a fair few fabric mods that got downloaded because people don't mark/say they are fabric....
Feel free to close if you don't think it's an issue.

**Comment by TelepathicGrunt** [comment]
Well this is a forge mod and you are on the 1.14 branch which is not as stable as the master branch. I remember dealing with that bug a bit ago but it should be fixed by now. Try this mod on the latest forge version and mod version and see if the issue persist.

**Comment by TelepathicGrunt** [comment]
If the issue is still present on the latest release, please open up a new issue. Hopefully it'll work for you now!
