### ISSUE TITLE
Crash at world creation / load - 1.16.4 - Forge 35.1.36

### ISSUE THREAD

**Issue by solarblindfull** [TelepathicGrunt/UltraAmplifiedMod#24]
Hello ! Thank for your mod !
I finded a world creation or load crash issue with your mod (V.9.0.1) as you see in the lastest log below.

[latest.txt](https://github.com/TelepathicGrunt/UltraAmplifiedDimension-Forge/files/5798631/latest.txt)

Can you see what's wrong please ?
Thank ! Have a good day !

**Comment by TelepathicGrunt** [comment]
closing this as we already got a thread going here: https://github.com/TelepathicGrunt/UltraAmplifiedDimension-Forge/issues/23
Files can be attached to comments btw. I'll reply on the other thread with some suggestions
