### ISSUE TITLE
UAD biomes spawning in Nether (poorly)

### ISSUE THREAD

**Issue by VallenFrostweaver** [TelepathicGrunt/UltraAmplifiedMod#27]
Minecraft 1.16.5
Forge 36.0.40
UAD 9.0.3
When exploring the Nether dimension, we found UAD biomes in the nether.
1. Not sure if UAD biomes are supposed to spawn in the Nether.
2. They don't connect well with surrounding biomes and look chunky.
Images attached below:
![uad2](https://user-images.githubusercontent.com/13642054/110246538-e07f6c80-7f5f-11eb-8421-4e58062bca0f.png)
![uad1](https://user-images.githubusercontent.com/13642054/110246540-e1b09980-7f5f-11eb-98d5-8de0f6dba03f.png)

**Comment by TelepathicGrunt** [comment]
I’m guessing you are using Oh The Biomes You’ll Go or another nether mod that is importing all nether categories. Please try going into their configs and blacklist UAD’s nether biomes to prevent the importing. Might also have to do UAD’s End biomes as well if they automatically import that too for the End

**Comment by VallenFrostweaver** [comment]
You are correct. I am using OTBYG. Thank you. Sounds like a good idea. Are all UAD biomes prefixed with "UAD" as I need to find a list of them to blacklist.

**Comment by TelepathicGrunt** [comment]
You can find all my biomes here
The prefix is `ultra_amplified_dimension:`
<https://github.com/TelepathicGrunt/UltraAmplifiedDimension-Forge/tree/master/src/main/resources/data/ultra_amplified_dimension/worldgen/biome>

So the biomes you'll need to blacklist are:

ultra_amplified_dimension:crimson_forest
ultra_amplified_dimension:nether_wastes
ultra_amplified_dimension:warped_forest
ultra_amplified_dimension:basalt_deltas
ultra_amplified_dimension:soul_sand_valley

let me know if this works

**Comment by VallenFrostweaver** [comment]
Will do. Might be a day or two though.

**Comment by TelepathicGrunt** [comment]
While I cant prevent other mods from pulling in my biomes into the nether, i did fix the liquid enclosing feature in my biomes so that if the sealevel is lowered for my dimension, it looks much better! 

A side-effect of that is it now makes UAD's nether biomes look amazing in the vanilla nether lmao
![image](https://user-images.githubusercontent.com/40846040/114643737-3dc7b580-9ca4-11eb-875e-c45bc8d652c4.png)

**Comment by VallenFrostweaver** [comment]
Sorry I never replied. Your previous method did work thank you
