### ISSUE TITLE
Server Startup Crash

### ISSUE THREAD

**Issue by NielsPilgaard** [TelepathicGrunt/UltraAmplifiedMod#6]
Servers running `ultra_amplified_dimension-1.15.2-7.2.2` crash on startup
https://gist.github.com/NillerMedDild/064c2a3e6581b0a71570baa2a10f7f26

### Versions
- ultra_amplified_dimension-1.15.2-7.2.2
- Forge-1.15.2-31.1.1

**Comment by TelepathicGrunt** [comment]
I never seen that error before and I'm not sure how it even occurred. Does it still happen when using 7.2.1? Does it also still happen when using just that mod alone? 

I'll ask friends to take a look at that crashlog to see if they have any ideas and hopefully I can patch it for the full release of 7.2.2

**Comment by NielsPilgaard** [comment]
I haven't tried 7.2.1 or standalone, I'll do that this evening :)

**Comment by NielsPilgaard** [comment]
Also happens with 7.2.2 standalone: https://gist.github.com/NillerMedDild/d181d3b05c27021aa878692275692548
It does not happen with 7.2.1 standalone.

**Comment by TelepathicGrunt** [comment]
Ok thank you! This basically shows me I screwed up somewhere when making 7.2.2 and I know where to start looking. This really helps me a lot! Thank you!

**Comment by TelepathicGrunt** [comment]
Ok I found the issue and the patch will be release with v7.2.2 full release. I'll archive the buggy beta version right now.

I'll close this issue once the full release is finished and approved to CurseForge. It should be done in a day or two. Thank you so much for reporting this issue!

**Comment by TelepathicGrunt** [comment]
v.7.2.2 is now fully release! https://www.curseforge.com/minecraft/mc-mods/ultra-amplified-mod/files/2881782

This issue shall be close now. :)
